name: Pull request CI

on: [pull_request]

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup reviewdog
      run: |
        mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
        echo ::add-path::$HOME/bin

    # Checkstyle
    - name: Run checkstyle
      working-directory: ./plugin
      run: mvn checkstyle:checkstyle -f checkstyle_pom.xml
    - name: Run reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cat plugin/target/checkstyle-result.xml | reviewdog -f=checkstyle -name="checkstyle" -reporter=github-pr-check

    # PMD
    - name: Run pmd
      working-directory: ./plugin
      run: mvn pmd:pmd -f checkstyle_pom.xml
    - name: Run reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cat plugin/target/pmd.txt | reviewdog -efm="%f:%l:	%m" -name="pmd" -reporter=github-pr-check

    # Build & compiler warnings
    - name: Build with Maven
      working-directory: ./plugin
      run: ./compile.sh | tee ../compile.log

    - name: Run reviewdog to report deprecation warnings
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cat compile.log | grep '^\[WARNING\].*\.java' | reviewdog -efm="[WARNING] %f:[%l,%c] %m" -name="compiler-warnings" -reporter=github-pr-check
